# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: miner.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bminer.proto\x12\x05miner\"\x94\x01\n\x12StartMiningRequest\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\r\n\x05\x61\x64\x64r1\x18\x02 \x01(\t\x12\r\n\x05\x61\x64\x64r2\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x04\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\x12\x0e\n\x06target\x18\x06 \x01(\t\x12\x12\n\ntime_limit\x18\x07 \x01(\r\x12\x0c\n\x04\x66lag\x18\x08 \x01(\r\"K\n\x13StartMiningResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\"(\n\x12PauseMiningRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"K\n\x13PauseMiningResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nstate_file\x18\x03 \x01(\t\"=\n\x13ResumeMiningRequest\x12\x12\n\nstate_file\x18\x01 \x01(\t\x12\x12\n\ntime_limit\x18\x02 \x01(\r\"L\n\x14ResumeMiningResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\"&\n\x10GetStatusRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"w\n\x11GetStatusResponse\x12\x11\n\tis_mining\x18\x01 \x01(\x08\x12\x14\n\x0ctotal_hashes\x18\x02 \x01(\x04\x12\x11\n\thash_rate\x18\x03 \x01(\x01\x12\x15\n\rcurrent_nonce\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t2\xa3\x02\n\x0cMinerService\x12\x44\n\x0bStartMining\x12\x19.miner.StartMiningRequest\x1a\x1a.miner.StartMiningResponse\x12\x44\n\x0bPauseMining\x12\x19.miner.PauseMiningRequest\x1a\x1a.miner.PauseMiningResponse\x12G\n\x0cResumeMining\x12\x1a.miner.ResumeMiningRequest\x1a\x1b.miner.ResumeMiningResponse\x12>\n\tGetStatus\x12\x17.miner.GetStatusRequest\x1a\x18.miner.GetStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'miner_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTMININGREQUEST']._serialized_start=23
  _globals['_STARTMININGREQUEST']._serialized_end=171
  _globals['_STARTMININGRESPONSE']._serialized_start=173
  _globals['_STARTMININGRESPONSE']._serialized_end=248
  _globals['_PAUSEMININGREQUEST']._serialized_start=250
  _globals['_PAUSEMININGREQUEST']._serialized_end=290
  _globals['_PAUSEMININGRESPONSE']._serialized_start=292
  _globals['_PAUSEMININGRESPONSE']._serialized_end=367
  _globals['_RESUMEMININGREQUEST']._serialized_start=369
  _globals['_RESUMEMININGREQUEST']._serialized_end=430
  _globals['_RESUMEMININGRESPONSE']._serialized_start=432
  _globals['_RESUMEMININGRESPONSE']._serialized_end=508
  _globals['_GETSTATUSREQUEST']._serialized_start=510
  _globals['_GETSTATUSREQUEST']._serialized_end=548
  _globals['_GETSTATUSRESPONSE']._serialized_start=550
  _globals['_GETSTATUSRESPONSE']._serialized_end=669
  _globals['_MINERSERVICE']._serialized_start=672
  _globals['_MINERSERVICE']._serialized_end=963
# @@protoc_insertion_point(module_scope)
